package Model;
// Generated Sep 28, 2023 8:50:15 PM by Hibernate Tools 4.3.1



/**
 * Categoriaproduto generated by hbm2java
 */
public class Categoriaproduto  implements java.io.Serializable {


     private Integer idCategoriaProduto;
     private String categoria;
     private String descricao;

    public Categoriaproduto() {
    }

	
    public Categoriaproduto(String categoria) {
        this.categoria = categoria;
    }
    public Categoriaproduto(String categoria, String descricao) {
       this.categoria = categoria;
       this.descricao = descricao;
    }
   
    public Integer getIdCategoriaProduto() {
        return this.idCategoriaProduto;
    }
    
    public void setIdCategoriaProduto(Integer idCategoriaProduto) {
        this.idCategoriaProduto = idCategoriaProduto;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


