package Model;
// Generated Sep 28, 2023 8:50:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empregado generated by hbm2java
 */
public class Empregado  implements java.io.Serializable {


     private Integer idEmpregado;
     private Funcaoempregado funcaoempregado;
     private String primeiroNome;
     private String apelido;
     private String email;
     private String senha;
     private Date dataNascimento;
     private char sexo;
     private Date dataCadastro;
     private String estado;
     private Boolean estadoB;
     private String enderecoResidencia;
     private int salario;
     private int nivel;
     private Set pedidos = new HashSet(0);
     private Set telefoneFuncionarios = new HashSet(0);

    public Empregado() {
    }

	
    public Empregado(String primeiroNome, String apelido, String email, String senha, char sexo, Date dataCadastro, String estado, String enderecoResidencia, int salario, int nivel) {
        this.primeiroNome = primeiroNome;
        this.apelido = apelido;
        this.email = email;
        this.senha = senha;
        this.sexo = sexo;
        this.dataCadastro = dataCadastro;
        this.estado = estado;
        this.enderecoResidencia = enderecoResidencia;
        this.salario = salario;
        this.nivel = nivel;
    }
    public Empregado(Funcaoempregado funcaoempregado, String primeiroNome, String apelido, String email, String senha, Date dataNascimento, char sexo, Date dataCadastro, String estado, Boolean estadoB, String enderecoResidencia, int salario, int nivel, Set pedidos, Set telefoneFuncionarios) {
       this.funcaoempregado = funcaoempregado;
       this.primeiroNome = primeiroNome;
       this.apelido = apelido;
       this.email = email;
       this.senha = senha;
       this.dataNascimento = dataNascimento;
       this.sexo = sexo;
       this.dataCadastro = dataCadastro;
       this.estado = estado;
       this.estadoB = estadoB;
       this.enderecoResidencia = enderecoResidencia;
       this.salario = salario;
       this.nivel = nivel;
       this.pedidos = pedidos;
       this.telefoneFuncionarios = telefoneFuncionarios;
    }
   
    public Integer getIdEmpregado() {
        return this.idEmpregado;
    }
    
    public void setIdEmpregado(Integer idEmpregado) {
        this.idEmpregado = idEmpregado;
    }
    public Funcaoempregado getFuncaoempregado() {
        return this.funcaoempregado;
    }
    
    public void setFuncaoempregado(Funcaoempregado funcaoempregado) {
        this.funcaoempregado = funcaoempregado;
    }
    public String getPrimeiroNome() {
        return this.primeiroNome;
    }
    
    public void setPrimeiroNome(String primeiroNome) {
        this.primeiroNome = primeiroNome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Boolean getEstadoB() {
        return this.estadoB;
    }
    
    public void setEstadoB(Boolean estadoB) {
        this.estadoB = estadoB;
    }
    public String getEnderecoResidencia() {
        return this.enderecoResidencia;
    }
    
    public void setEnderecoResidencia(String enderecoResidencia) {
        this.enderecoResidencia = enderecoResidencia;
    }
    public int getSalario() {
        return this.salario;
    }
    
    public void setSalario(int salario) {
        this.salario = salario;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getTelefoneFuncionarios() {
        return this.telefoneFuncionarios;
    }
    
    public void setTelefoneFuncionarios(Set telefoneFuncionarios) {
        this.telefoneFuncionarios = telefoneFuncionarios;
    }




}


