package Model;
// Generated Sep 28, 2023 8:50:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Encomenda generated by hbm2java
 */
public class Encomenda  implements java.io.Serializable {


     private Integer idEncomenda;
     private Cliente cliente;
     private String situacao;
     private int custoEntrega;
     private Date dataEncomenda;
     private Set vendas = new HashSet(0);
     private Set itemcardapios = new HashSet(0);

    public Encomenda() {
    }

	
    public Encomenda(String situacao, int custoEntrega, Date dataEncomenda) {
        this.situacao = situacao;
        this.custoEntrega = custoEntrega;
        this.dataEncomenda = dataEncomenda;
    }
    public Encomenda(Cliente cliente, String situacao, int custoEntrega, Date dataEncomenda, Set vendas, Set itemcardapios) {
       this.cliente = cliente;
       this.situacao = situacao;
       this.custoEntrega = custoEntrega;
       this.dataEncomenda = dataEncomenda;
       this.vendas = vendas;
       this.itemcardapios = itemcardapios;
    }
   
    public Integer getIdEncomenda() {
        return this.idEncomenda;
    }
    
    public void setIdEncomenda(Integer idEncomenda) {
        this.idEncomenda = idEncomenda;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public int getCustoEntrega() {
        return this.custoEntrega;
    }
    
    public void setCustoEntrega(int custoEntrega) {
        this.custoEntrega = custoEntrega;
    }
    public Date getDataEncomenda() {
        return this.dataEncomenda;
    }
    
    public void setDataEncomenda(Date dataEncomenda) {
        this.dataEncomenda = dataEncomenda;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Set getItemcardapios() {
        return this.itemcardapios;
    }
    
    public void setItemcardapios(Set itemcardapios) {
        this.itemcardapios = itemcardapios;
    }




}


