package Model;
// Generated Sep 28, 2023 8:50:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcaoempregado generated by hbm2java
 */
public class Funcaoempregado  implements java.io.Serializable {


     private Integer idFuncao;
     private String funcao;
     private String descricao;
     private Boolean status;
     private Set empregados = new HashSet(0);

    public Funcaoempregado() {
    }

	
    public Funcaoempregado(String funcao) {
        this.funcao = funcao;
    }
    public Funcaoempregado(String funcao, String descricao, Boolean status, Set empregados) {
       this.funcao = funcao;
       this.descricao = descricao;
       this.status = status;
       this.empregados = empregados;
    }
   
    public Integer getIdFuncao() {
        return this.idFuncao;
    }
    
    public void setIdFuncao(Integer idFuncao) {
        this.idFuncao = idFuncao;
    }
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getEmpregados() {
        return this.empregados;
    }
    
    public void setEmpregados(Set empregados) {
        this.empregados = empregados;
    }




}


