package Model;
// Generated Sep 28, 2023 8:50:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Itemcardapio generated by hbm2java
 */
public class Itemcardapio  implements java.io.Serializable {


     private Integer idItemCardapio;
     private Encomenda encomenda;
     private Pedido pedido;
     private String nomeItem;
     private int precoUnitario;
     private Boolean estado;
     private Set produtos = new HashSet(0);

    public Itemcardapio() {
    }

	
    public Itemcardapio(String nomeItem, int precoUnitario) {
        this.nomeItem = nomeItem;
        this.precoUnitario = precoUnitario;
    }
    public Itemcardapio(Encomenda encomenda, Pedido pedido, String nomeItem, int precoUnitario, Boolean estado, Set produtos) {
       this.encomenda = encomenda;
       this.pedido = pedido;
       this.nomeItem = nomeItem;
       this.precoUnitario = precoUnitario;
       this.estado = estado;
       this.produtos = produtos;
    }
   
    public Integer getIdItemCardapio() {
        return this.idItemCardapio;
    }
    
    public void setIdItemCardapio(Integer idItemCardapio) {
        this.idItemCardapio = idItemCardapio;
    }
    public Encomenda getEncomenda() {
        return this.encomenda;
    }
    
    public void setEncomenda(Encomenda encomenda) {
        this.encomenda = encomenda;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public String getNomeItem() {
        return this.nomeItem;
    }
    
    public void setNomeItem(String nomeItem) {
        this.nomeItem = nomeItem;
    }
    public int getPrecoUnitario() {
        return this.precoUnitario;
    }
    
    public void setPrecoUnitario(int precoUnitario) {
        this.precoUnitario = precoUnitario;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


