package Model;
// Generated Sep 28, 2023 8:50:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idProduto;
     private Itemcardapio itemcardapio;
     private Integer categoriaProduto;
     private String nomeProduto;
     private int quantidadeProduto;
     private int precoUnitarioProduto;
     private int precoCompraProduto;
     private Date dataCompraProduto;
     private Date dataValidadeProduto;

    public Produto() {
    }

	
    public Produto(String nomeProduto, int quantidadeProduto, int precoUnitarioProduto, int precoCompraProduto, Date dataCompraProduto, Date dataValidadeProduto) {
        this.nomeProduto = nomeProduto;
        this.quantidadeProduto = quantidadeProduto;
        this.precoUnitarioProduto = precoUnitarioProduto;
        this.precoCompraProduto = precoCompraProduto;
        this.dataCompraProduto = dataCompraProduto;
        this.dataValidadeProduto = dataValidadeProduto;
    }
    public Produto(Itemcardapio itemcardapio, Integer categoriaProduto, String nomeProduto, int quantidadeProduto, int precoUnitarioProduto, int precoCompraProduto, Date dataCompraProduto, Date dataValidadeProduto) {
       this.itemcardapio = itemcardapio;
       this.categoriaProduto = categoriaProduto;
       this.nomeProduto = nomeProduto;
       this.quantidadeProduto = quantidadeProduto;
       this.precoUnitarioProduto = precoUnitarioProduto;
       this.precoCompraProduto = precoCompraProduto;
       this.dataCompraProduto = dataCompraProduto;
       this.dataValidadeProduto = dataValidadeProduto;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public Itemcardapio getItemcardapio() {
        return this.itemcardapio;
    }
    
    public void setItemcardapio(Itemcardapio itemcardapio) {
        this.itemcardapio = itemcardapio;
    }
    public Integer getCategoriaProduto() {
        return this.categoriaProduto;
    }
    
    public void setCategoriaProduto(Integer categoriaProduto) {
        this.categoriaProduto = categoriaProduto;
    }
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }
    public int getQuantidadeProduto() {
        return this.quantidadeProduto;
    }
    
    public void setQuantidadeProduto(int quantidadeProduto) {
        this.quantidadeProduto = quantidadeProduto;
    }
    public int getPrecoUnitarioProduto() {
        return this.precoUnitarioProduto;
    }
    
    public void setPrecoUnitarioProduto(int precoUnitarioProduto) {
        this.precoUnitarioProduto = precoUnitarioProduto;
    }
    public int getPrecoCompraProduto() {
        return this.precoCompraProduto;
    }
    
    public void setPrecoCompraProduto(int precoCompraProduto) {
        this.precoCompraProduto = precoCompraProduto;
    }
    public Date getDataCompraProduto() {
        return this.dataCompraProduto;
    }
    
    public void setDataCompraProduto(Date dataCompraProduto) {
        this.dataCompraProduto = dataCompraProduto;
    }
    public Date getDataValidadeProduto() {
        return this.dataValidadeProduto;
    }
    
    public void setDataValidadeProduto(Date dataValidadeProduto) {
        this.dataValidadeProduto = dataValidadeProduto;
    }




}


