package Model;
// Generated Sep 28, 2023 8:50:15 PM by Hibernate Tools 4.3.1



/**
 * TelefoneFuncionario generated by hbm2java
 */
public class TelefoneFuncionario  implements java.io.Serializable {


     private Integer idTelefoneCli;
     private Empregado empregado;
     private int contacto;

    public TelefoneFuncionario() {
    }

	
    public TelefoneFuncionario(int contacto) {
        this.contacto = contacto;
    }
    public TelefoneFuncionario(Empregado empregado, int contacto) {
       this.empregado = empregado;
       this.contacto = contacto;
    }
   
    public Integer getIdTelefoneCli() {
        return this.idTelefoneCli;
    }
    
    public void setIdTelefoneCli(Integer idTelefoneCli) {
        this.idTelefoneCli = idTelefoneCli;
    }
    public Empregado getEmpregado() {
        return this.empregado;
    }
    
    public void setEmpregado(Empregado empregado) {
        this.empregado = empregado;
    }
    public int getContacto() {
        return this.contacto;
    }
    
    public void setContacto(int contacto) {
        this.contacto = contacto;
    }




}


