package Model;
// Generated Sep 28, 2023 8:50:15 PM by Hibernate Tools 4.3.1



/**
 * Telefonecliente generated by hbm2java
 */
public class Telefonecliente  implements java.io.Serializable {


     private Integer idTelefoneCliente;
     private Cliente cliente;
     private Integer contacto;

    public Telefonecliente() {
    }

    public Telefonecliente(Cliente cliente, Integer contacto) {
       this.cliente = cliente;
       this.contacto = contacto;
    }
   
    public Integer getIdTelefoneCliente() {
        return this.idTelefoneCliente;
    }
    
    public void setIdTelefoneCliente(Integer idTelefoneCliente) {
        this.idTelefoneCliente = idTelefoneCliente;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Integer getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Integer contacto) {
        this.contacto = contacto;
    }




}


